datasource:
  school:
    url: jdbc:mysql://localhost:3306/schooldb?userSSL=false&serverTimezone=UTC
    username: school
    password: school
  student:
    url: jdbc:mysql://localhost:3306/studentdb?userSSL=false&serverTimezone=UTC
    username: student
    password: student
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true